# The workflow is intended to be used from a workflow run
# as it will pick the artifacts from the triger (through workflow_id)
name: windows-e2e

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:

env:
  IMAGE_NAME_E2E: macadam-e2e

jobs:
  build-qe:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Build qe oci image for windows-amd64
        run: |
          # e2e
          ARCH=amd64 OS=windows make containerized_e2e
          podman save -o ${{ env.IMAGE_NAME_E2E }}-windows-amd64.tar \
            ${{ env.IMAGE_NAME_E2E}}:windows-amd64
      - name: Upload e2e windows-amd64
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.IMAGE_NAME_E2E }}-windows-amd64
          path: ${{ env.IMAGE_NAME_E2E }}-windows-amd64.tar
  windows-qe:
    needs: build-qe
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: hyperv
            url: "https://crcqe-asia.s3.ap-south-1.amazonaws.com/macadam-image/Fedora-Cloud-Base-Azure-43-1.6.x86_64.vhd"
          - name: wsl
            url: "https://mirror.stream.centos.org/SIGs/10-stream/altimages/images/wsl/x86_64/CentOS-Stream-Image-WSL-Base.x86_64-10-202601110111.wsl"
    env:
      windows-version: '11'
      windows-featurepack: '23h2-ent'
    permissions:
      statuses: write # needed to update commit status (pending/failure/sucess)
      checks: write # as documented in https://github.com/mikepenz/action-junit-report?tab=readme-ov-file#pr-run-permissions

    steps:
    - name: Download qe oci image
      id: download-qe-oci-image-artifact
      uses: actions/download-artifact@v8
      with:
        name: ${{ env.IMAGE_NAME_E2E }}-windows-amd64

    - name: Correlate
      run: |
        # Get origin commit sha for testing
        commit_sha=${{ github.event.workflow_run.head_commit.id }}
        if [[ -z "${commit_sha}" ]] || [[ "${commit_sha}" == null ]]; then
          # if .head_commit.id is empty, then .head_sha is used as commit instead
          commit_sha=${{ github.event.workflow_run.head_sha }}
        fi
        echo "commit_sha=${commit_sha}" >> "$GITHUB_ENV"

        # Set status_context
        status_context="ci/gh/e2e"
        status_context="${status_context}/windows-${{env.windows-version}}-${{env.windows-featurepack}}-${{ matrix.image.name }}"
        echo "status_context=${status_context}" >> "$GITHUB_ENV"

    - name: Add status to the PR check
      run: |
        set -xuo pipefail
        # Status msg
        data="{\"state\":\"pending\""
        data="${data},\"description\":\"Running e2e on Windows\""
        data="${data},\"context\":\"${{ env.status_context }}\""
        data="${data},\"target_url\":\"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}"
        # Create status by API call
        curl -L -v -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ env.commit_sha }} \
          -d "${data}"

    - name: Create Windows instance
      run: |
        sudo chmod -R 777 $GITHUB_WORKSPACE
        # Create instance
        podman run -d --name windows-create --rm \
          -v ${PWD}:/workspace:z \
          -e ARM_TENANT_ID=${{secrets.ARM_TENANT_ID}} \
          -e ARM_SUBSCRIPTION_ID=${{secrets.ARM_SUBSCRIPTION_ID}} \
          -e ARM_CLIENT_ID=${{secrets.ARM_CLIENT_ID}} \
          -e ARM_CLIENT_SECRET='${{secrets.ARM_CLIENT_SECRET}}' \
          -e AZURE_STORAGE_ACCOUNT='${{ secrets.AZURE_STORAGE_ACCOUNT }}' \
          -e AZURE_STORAGE_KEY='${{ secrets.AZURE_STORAGE_KEY }}' \
          quay.io/redhat-developer/mapt:v0.12.1 azure \
            windows create \
            --project-name 'windows-desktop-${{ env.windows-version }}-${{ env.windows-featurepack }}-macadam-${{ matrix.image.name }}' \
            --backed-url azblob://crc-qenvs-state/${{ github.repository }}-${{ github.run_id }}-${{ matrix.image.name }} \
            --conn-details-output '/workspace' \
            --nested-virt \
            --cpus 8 \
            --windows-version '${{env.windows-version}}' \
            --windows-featurepack '${{env.windows-featurepack}}' \
            --tags project=openshift-local,source=github,org=${{github.repository_owner}},run=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \
            --spot \
            --spot-excluded-regions southafricawest,australiacentral2,eastus2euap
        podman logs -f windows-create
        sudo chown runner:runner host username id_rsa

    - name: Run macadam e2e
      run: |
        # load image
        podman load -i ${{ env.IMAGE_NAME_E2E }}-windows-amd64.tar
        # run
        ImageURL="${{ matrix.image.url }}"
        cmd="macadam-test/run.ps1 -imageUrl $ImageURL "

        podman run --rm -d --name windows-e2e-test \
          -e OS=windows \
          -e TARGET_HOST=$(cat host) \
          -e TARGET_HOST_USERNAME=$(cat username) \
          -e TARGET_HOST_KEY_PATH=/data/id_rsa \
          -e TARGET_FOLDER=macadam-test  \
          -e TARGET_RESULTS=results \
          -e OUTPUT_FOLDER=/data \
          -e DEBUG=true \
          -v $PWD:/data:z \
          ${{ env.IMAGE_NAME_E2E }}:windows-amd64 \
              ${cmd}
        podman logs -f windows-e2e-test

    - name: Test Report
      id: test-report
      uses: mikepenz/action-junit-report@v6
      if: always()
      with:
        fail_on_failure: true
        include_passed: true
        detailed_summary: true
        require_tests:  true
        report_paths: '**/*.xml'

    - name: Upload e2e results
      uses: actions/upload-artifact@v7
      if: always()
      with:
        name: windows-${{env.windows-version}}${{env.windows-featurepack}}-${{ matrix.image.name }}
        path: |
          **/*.xml
          **/*.results
          **/*.log

    - name: Update status of the PR check
      if: always()
      run: |
        set -xuo
        # Status msg
        data="{\"state\":\"success\""
        if [[ ${{steps.test-report.outcome}} != "success" ]]; then
          data="{\"state\":\"failure\""
        fi
        data="${data},\"description\":\"Finished e2e test on Windows\""
        data="${data},\"context\":\"${{ env.status_context }}\""
        data="${data},\"target_url\":\"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}"
        # Create status by API call
        curl -L -v -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ env.commit_sha }} \
          -d "${data}"

    - name: Destroy instance
      if: always()
      run: |
        # Make sure lock is removed
        rm -rf .pulumi/locks/*
        # Destroy
        podman run -d --name windows-destroy --rm \
          -v ${PWD}:/workspace:z \
          -e ARM_TENANT_ID=${{secrets.ARM_TENANT_ID}} \
          -e ARM_SUBSCRIPTION_ID=${{secrets.ARM_SUBSCRIPTION_ID}} \
          -e ARM_CLIENT_ID=${{secrets.ARM_CLIENT_ID}} \
          -e ARM_CLIENT_SECRET='${{secrets.ARM_CLIENT_SECRET}}' \
          -e AZURE_STORAGE_ACCOUNT='${{ secrets.AZURE_STORAGE_ACCOUNT }}' \
          -e AZURE_STORAGE_KEY='${{ secrets.AZURE_STORAGE_KEY }}' \
          quay.io/redhat-developer/mapt:v0.12.1 azure \
            windows destroy \
            --project-name 'windows-desktop-${{ env.windows-version }}-${{ env.windows-featurepack }}-macadam-${{ matrix.image.name }}' \
            --backed-url azblob://crc-qenvs-state/${{ github.repository }}-${{ github.run_id }}-${{ matrix.image.name }}
        podman logs -f windows-destroy
