name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        go:
        - '1.23.8'
        - '1.24.2'
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: >-
          WORKAROUND: Fetch tags that points to the revisions
          checked-out(actions/checkout#1467)
        run: |-
          git fetch --tags --force

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: make cross
      - name: Upload macadam artifact
        if: matrix.go == '1.23.8'
        uses: actions/upload-artifact@v4
        with:
          name: macadam binaries
          path: "./bin/*"


  test:
    needs: build
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        - macos-13
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'
      - name: Test
        run: make test

  e2e:
    needs: build
    strategy:
      matrix:
        os:
        - ubuntu-24.04
        - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      ADDITIONAL_TOOLS: ${{ github.workspace }}/tools
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: macadam binaries
          path: ./bin
      - name: Install qemu-img (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y qemu-utils qemu-system
      - name: Download gvproxy
        if: runner.os == 'Linux'
        run: |
          wget https://github.com/containers/gvisor-tap-vsock/releases/download/v0.8.5/gvproxy-linux-amd64 -O ${{ github.workspace }}/tools/gvproxy
          chmod +x ${{ github.workspace }}/tools/gvproxy
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'oldstable'
      - name: Grant execute permissions
        if: runner.os == 'Linux'
        run: chmod +x ./bin/*
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: lstocchi

  lint:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'
      - name: Run 'make check'
        run: make check
